# Generated by Django 2.2.4 on 2021-03-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_auto_20210301_1424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='hobby',
        ),
        migrations.RemoveField(
            model_name='user',
            name='info',
        ),
    ]
